org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true

mod_id=autyism-meteor
mod_name=Autyism's Meteor Addon
mod_version=1.0.0
maven_group=com.autyism.meteor
archives_base_name=autyism-meteor-addon

minecraft_version=1.21.11
loader_version=0.19.3
fabric_version=0.140.2+1.21.11
